export type StudentDepartmentCode = "cse" | "ece" | "ee";

export type StudentDepartment = {
  code: StudentDepartmentCode;
  short: string;
  name: string;
};

export type StudentProfile = {
  id: string;
  fullName: string;
  department: StudentDepartmentCode;
  year: string;
  headline?: string;
  imageFile?: string;
  imageUrl?: string;
  linkedin?: string;
  github?: string;
  leetcode?: string;
  portfolio?: string;
};

export const studentDepartments: StudentDepartment[] = [
  { code: "cse", short: "CSE", name: "Computer Science Engineering" },
  { code: "ece", short: "ECE", name: "Electronics & Communication Engineering" },
  { code: "ee", short: "EE", name: "Electrical Engineering" },
];

const STUDENTS_PER_DEPARTMENT = 120;

function createPlaceholderProfiles(
  department: StudentDepartmentCode,
  departmentLabel: string,
  count: number
): StudentProfile[] {
  return Array.from({ length: count }, (_, index) => {
    const sequence = String(index + 1).padStart(3, "0");
    const fullName = `${departmentLabel} Student ${sequence}`;

    return {
      id: `${department}-placeholder-${sequence}`,
      fullName,
      department,
      year: "B.Tech 3rd Year",
      headline: `Focused on ${departmentLabel} core projects and placement preparation.`,
      imageFile: `${fullName.replaceAll(" ", "_")}.jpg`,
    };
  });
}

const importedProfiles: StudentProfile[] = [
  {
    id: "ece-23294917015",
    fullName: "Shreyas Singh",
    department: "ece",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1zcZ697atuTDbeqGabRr9h2P_xLye2wT5",
    linkedin: "https://www.linkedin.com/in/shreyas-singh-7883bb206/",
    github: "https://github.com/Shreyasilver22",
    leetcode: "https://hdlbits.01xz.net/wiki/Special:VlgStats/120DEE1F9EFAE650",
  },
  {
    id: "cse-23293916135",
    fullName: "Sneha Gupta",
    department: "cse",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1zZQqg0C1N6pWPtUDGYhs_ac4NnF4kjGL",
    linkedin: "https://www.linkedin.com/in/sneha-gupta-bb579829a/",
    github: "https://github.com/Snehagupta-01",
    leetcode: "https://leetcode.com/u/Snehagupta2042/",
  },
  {
    id: "ece-23294917110",
    fullName: "GAVENDRA SINGH",
    department: "ece",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1zE6vtIG-g7yjhXd6V2FoVoQpve7h1wNc",
    linkedin: "https://www.bing.com/search?pglt=299&q=linkdin&cvid=b3453ae3b856453f92d1e3676072e85d&gs_lcrp=EgRlZGdlKgYIABBFGDsyBggAEEUYOzIGCAEQRRg7MgYIAhBFGDzSAQkxNDM3M2owajGoAgCwAgA&FORM=ANNTA1&PC=U531",
    github: "https://github.com/gavendra12s",
  },
  {
    id: "cse-23293916060",
    fullName: "Tamanna Sharma",
    department: "cse",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1SIi9aLUhVtMmkl6-7hOH3QN4YusievGb",
    github: "https://github.com/tamz2020?tab=repositories",
  },
  {
    id: "ece-23294917061",
    fullName: "Eshant Pundhir",
    department: "ece",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1CyWJKtefenZF7VYa4Ma-ibTNVJ1z5mWn",
    linkedin: "https://www.linkedin.com/in/eshant-pundhir-609961296?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    github: "https://github.com/eshant7505",
  },
  {
    id: "cse-23293916084",
    fullName: "Ashish Pal",
    department: "cse",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1hXUmJkQHA2_LHEPOjGkaPGlykzkxp9NN",
    linkedin: "https://www.linkedin.com/in/ashish-pal-373a5b2a6",
    github: "https://github.com/apal632162006",
    leetcode: "https://leetcode.com/u/apal63216",
  },
  {
    id: "ece-23294917090",
    fullName: "Goldi Kumari",
    department: "ece",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1vnNVFVkEGUoKQnjAVQmXEcfh0Oe_CDSe",
    linkedin: "https://www.linkedin.com/in/goldikumari12/",
    github: "http://github.com/Gold-1234",
    leetcode: "https://leetcode.com/u/goldenhour_/",
  },
  {
    id: "cse-23293916071",
    fullName: "Shriyam Baloni",
    department: "cse",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1GLoDy6-8CLhquCxy3GDRqTRg-UQ5QHte",
    linkedin: "https://www.linkedin.com/in/shriyam-baloni",
    github: "https://github.com/CodeShrek",
    leetcode: "https://leetcode.com/u/Shri_Yam",
  },
  {
    id: "cse-23293916058",
    fullName: "Khush deep singh",
    department: "cse",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1YRSx02z91ydIom10bcu4-Xgf-GCa4jp4",
    linkedin: "https://www.linkedin.com/in/khushdeep-singh-2a5577336",
    github: "https://github.com/Khushdeep058",
    leetcode: "https://codeforces.com/profile/khushdeepsingh5973",
  },
  {
    id: "ece-23294917083",
    fullName: "ULLI RAGHAVENDRA",
    department: "ece",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1fiKB1jHJMqKY0hWVqbtEV98imRjvpQSo",
    linkedin: "https://www.linkedin.com/in/raghavaulli",
  },
  {
    id: "cse-23293916132",
    fullName: "Nizamuddin",
    department: "cse",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1BpdXIFRAVj4S51aaXUK9__9FE0Y6gjFw",
    linkedin: "https://www.linkedin.com/in/nizamuddin12",
    github: "https://github.com/Nizamuddin1N",
    leetcode: "https://leetcode.com/u/Nizamuudin",
  },
  {
    id: "ece-23294917128",
    fullName: "Khushi Sihag",
    department: "ece",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1yi3ViHOqfWT4EVdrKHLJrJ8Nh0W1ZB2o",
    linkedin: "https://www.linkedin.com/in/khushi-sihag-57b64532b",
  },
  {
    id: "cse-23293916066",
    fullName: "AKSHAT",
    department: "cse",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1h9nBpGC9g4PCDWwSXo0MXJwWjYK0Ob4j",
    linkedin: "https://www.linkedin.com/in/akshat-akshat-0524b32b1/",
    github: "https://github.com/AKSHATcseb",
    leetcode: "https://www.naukri.com/code360/profile/AkshatAkshat",
  },
  {
    id: "cse-23293916092",
    fullName: "Humendra Narayan",
    department: "cse",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1wjmNs0iXQtQVc8Krtu9bmwu6wrb0mTYw",
    linkedin: "https://www.linkedin.com/in/humendra-narayan-76980428b/",
    github: "https://github.com/Humendra18",
    leetcode: "https://www.hackerrank.com/profile/Bhardwajhumendra",
  },
  {
    id: "cse-23293916081",
    fullName: "Jitesh Chakma",
    department: "cse",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1keSi4AVzJARlw9R8O8nWFQBBF3Ixnmz-",
    linkedin: "https://www.linkedin.com/in/jitesh-chakma-975672380?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    github: "https://github.com/jiteshchakma36",
    leetcode: "https://leetcode.com/u/jiteshfema/",
  },
  {
    id: "cse-23293916121",
    fullName: "BRIJESH KUMAR MORYA",
    department: "cse",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1KbzM-rYZg4Jk-HxDx6lcpXYrmJpCVVGH",
    linkedin: "https://linkedin.com/in/brijeshkumarmorya",
    github: "https://github.com/brijeshkumarmorya",
    leetcode: "https://leetcode.com/u/brijeshkumarmorya",
  },
  {
    id: "ece-23294917081",
    fullName: "Mohit Kumar Thakur",
    department: "ece",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1FaB00bPVBYrAmgxy9kATEh9zR72J4UyL",
    linkedin: "https://www.linkedin.com/in/mohitkumarthakur/",
    github: "https://github.com/Mohit-Kumar-Thakur",
    leetcode: "https://leetcode.com/u/MohitKumarThakur/",
  },
  {
    id: "ee-23295918029",
    fullName: "Ekansh Dubey",
    department: "ee",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1N2bcgAensxDw93jvf2Zn6zcMETEWXqYl",
    linkedin: "https://www.linkedin.com/in/ekansh-dubey-0b2808227/",
    github: "https://github.com/ekansh-exe",
    leetcode: "https://www.codechef.com/users/ekansh_28",
  },
  {
    id: "ece-23294917108",
    fullName: "Abhishek Kumar",
    department: "ece",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1mwwnDOw2ipNov35e8jBzDO11YL62q3QN",
    linkedin: "https://www.linkedin.com/in/abhishek-kumar-6a90812b4/",
    github: "https://github.com/abhishek23DU108",
  },
  {
    id: "ee-23295918030",
    fullName: "Pankaj Kumar",
    department: "ee",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1IL5-NU1Qsc8NBEiWgELBsUvGPvRJoM6X",
    linkedin: "https://www.linkedin.com/in/pankaj-kumar-871493356/",
    github: "https://github.com/pankajkumar022023-cloud",
  },
  {
    id: "ece-23294917007",
    fullName: "Aayush Chauhan",
    department: "ece",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1No63VeMfKgu09zW1Z5hLkXSS0v36hH8R",
    linkedin: "https://www.linkedin.com/in/aayushchauhan019/",
    github: "https://github.com/aayush010904",
    leetcode: "https://leetcode.com/u/aayush010904/",
  },
  {
    id: "cse-23293916076",
    fullName: "Yashika",
    department: "cse",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1kptjMrCBFcQYDCNf3IXSTGB__IlGfv0E",
    linkedin: "https://www.linkedin.com/in/yashika-4b9a323a7",
    github: "https://github.com/7Yashika",
    leetcode: "https://leetcode.com/u/Fh16nFMT4o/",
    portfolio: "https://www.figma.com/@fc8568d3_8eeb_4",
  },
  {
    id: "ece-23294917032",
    fullName: "Aman Sengar",
    department: "ece",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1ZYz4TYigUgPLxKRoCXP-S0KUdc2dxlu2",
    linkedin: "https://www.linkedin.com/in/aman-sengar-04ba373b8?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    github: "https://github.com/amansengarece",
    leetcode: "https://leetcode.com/u/amansengar0610/",
  },
  {
    id: "cse-23293916086",
    fullName: "Arnav Gupta",
    department: "cse",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1Encc7TWLmdzZj6WICErzk3P1_Ssvt9si",
    linkedin: "https://www.linkedin.com/in/arnav-gupta-6083ba306/",
    github: "https://github.com/arnavce",
    leetcode: "https://leetcode.com/u/Arnav_221/",
  },
  {
    id: "cse-23293916146",
    fullName: "Jaydeep Gupta",
    department: "cse",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1p3yp1gqe7m7QcuEweDTjFJW4qMIH24Jp",
    linkedin: "https://www.linkedin.com/in/jaydeep-gupta-7912ab360/",
    github: "https://github.com/JaydeepDU",
    leetcode: "https://leetcode.com/u/1tNvTHLXR4/",
  },
  {
    id: "ece-23294917099",
    fullName: "Ayush Kumar",
    department: "ece",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1EUkng260G4eftpAqKdm4NAncpCu1p2IC",
    linkedin: "https://www.linkedin.com/in/ayush-kumar-a19b7b293",
    github: "https://github.com/Aayush0004",
    leetcode: "https://leetcode.com/u/aayush0004/",
  },
  {
    id: "cse-23293916098",
    fullName: "Vishank Saini",
    department: "cse",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1EG4anGjdMjIDKY-gUpVyarjF3QjkHPw9",
    linkedin: "https://www.linkedin.com/in/vishank-saini-077854289",
    github: "https://github.com/Vishank123",
    leetcode: "https://leetcode.com/u/vishank_saini/",
  },
  {
    id: "cse-23293916091",
    fullName: "Pratyush Negi",
    department: "cse",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1f9RBw_OKA1GKIgjPHL-kLel-L3HBZwx1",
    linkedin: "https://www.linkedin.com/in/25pratyushnegi",
    github: "https://github.com/Pratyush-Negi25",
    leetcode: "https://www.kaggle.com/pratyushddn",
  },
  {
    id: "ece-23294917148",
    fullName: "Shashikant Kumar Bind",
    department: "ece",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1mPIEFSnSIy8wK_8oh1nuar9NZDydGdf2",
    linkedin: "https://www.linkedin.com/in/shashikant-kumar-bind-20a25b2a7/",
    github: "https://github.com/stechbindra2",
    leetcode: "https://github.com/stechbindra2",
  },
  {
    id: "ece-23294917111",
    fullName: "Ayush Narwariya",
    department: "ece",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=18hFAKq-ph1zvhO34sVFdSN9iNow-yLmb",
    linkedin: "https://in.linkedin.com/in/ayush-narwariya-348b683b8",
    github: "https://github.com/ToXicOp28",
  },
  {
    id: "ece-23294917134",
    fullName: "Shivanand",
    department: "ece",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1qnhJjagY6SHN7FgfneXu0N4yduRsIuMv",
    linkedin: "https://www.linkedin.com/in/shivanand-saraswati-106bb3321",
    github: "https://github.com/Shivanand80-tech",
    leetcode: "https://leetcode.com/VHX8rBdAmf",
  },
  {
    id: "ece-23294917097",
    fullName: "Shriyanshu Kumar Chaudhary",
    department: "ece",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1Id0PMR9pjjGSdYh20O0jIJ_h1giBsCG6",
    linkedin: "https://www.linkedin.com/in/shriyanshu-chaudhary",
    github: "https://github.com/Shriyansh22",
  },
  {
    id: "ece-23294917014",
    fullName: "Arpit Garg",
    department: "ece",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1Am2LFWq2W4dokz73WFLW4uxxYD3_2jvw",
    linkedin: "https://www.linkedin.com/in/arpit-garg-6632a52bb/",
    github: "https://github.com/Agarg0021",
    leetcode: "https://leetcode.com/u/JbLg3kq8Li/",
  },
  {
    id: "cse-23293916128",
    fullName: "Rohit Jambhulkar",
    department: "cse",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=18CrwSLreKEwqZWu378UKxOwNKcAqqrE3",
    linkedin: "https://www.linkedin.com/in/rohit-jambhulkar-a7822b322/",
    github: "https://github.com/Heishenberg",
    leetcode: "https://leetcode.com/u/e3GFyQ5uAg/",
  },
  {
    id: "ece-23294917085",
    fullName: "Harshit Gupta",
    department: "ece",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1nZuRZvAQ5_Tz5gFmQ025jYmV8XusOpNp",
    linkedin: "https://www.linkedin.com/in/harshit-gupta-4a50b23a9",
    github: "https://github.com/Harshitgupta63?tab=overview&from=2026-03-01&to=2026-03-20",
    leetcode: "https://leetcode.com/u/harshitgupta2004/",
  },
  {
    id: "ee-23295918020",
    fullName: "VAIBHAV TANEJA",
    department: "ee",
    year: "B.Tech 3rd Year",
    headline: "Student profile submitted via Placement Form.",
    imageUrl: "https://drive.google.com/uc?export=view&id=1RNu3kiSsAMevrvxnN5p8YuCsfV1Eb1kE",
    linkedin: "https://www.linkedin.com/in/vaibhav-taneja-073ab6216",
    github: "https://github.com/vaibhavtaneja15?tab=repositories",
  },
];

export const studentProfiles: StudentProfile[] = studentDepartments.flatMap((department) => {
  const importedForDepartment = importedProfiles.filter((profile) => profile.department === department.code);
  const placeholderCount = Math.max(STUDENTS_PER_DEPARTMENT - importedForDepartment.length, 0);
  const placeholders = createPlaceholderProfiles(department.code, department.short, placeholderCount);

  return [...importedForDepartment, ...placeholders];
});
